name: Build and Release Metablog Theme

on:
  push:
    tags:
      - 'v*.*.*'     # Trigger on version tags like v1.0.0
    branches:
      - main         # Also trigger on push to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, dom, curl, fileinfo, json, libxml
          tools: composer

      - name: Install Composer dependencies
        run: composer install --no-dev --prefer-dist

      - name: Install Node.js dependencies
        run: npm install

      - name: Build assets
        run: npm run build

      - name: Create ZIP package
        run: |
          zip -r metablog.zip . -x "node_modules/*" ".git/*" "tests/*" "resources/*"
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            mv metablog.zip metablog-dev.zip
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          files: |
            ${{ github.event.repository.name }}.zip
            ${{ github.event.repository.name }}-dev.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main'

